### ISSUE TITLE
WASM Modules should be loaded via an Image

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#127]
**What**

When providing a WASM module, we should load it via an image registry such as quay. This will allow us to fall in line with how the rest of the components are delivered and also used the same processes for building, testing , scanning etc

**Comment by rahulanand16nov** [comment]
Not possible when inserting filters with `EnvoyFilter` but is with `WasmPlugin` which is in alpha right now.

**Comment by maleck13** [comment]
@alexsnaps

**Comment by maleck13** [comment]
https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/

**Comment by rahulanand16nov** [comment]
https://github.com/Kuadrant/kuadrant-controller/pull/152 completes the issue.
