### ISSUE TITLE
New RateLimitPolicy demo for showing Gateway support

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#132]
@rahulanand16nov could you propose a new flow for the demo here based on the feedback received on the first one

Currently the RLP implementation supports a form of override functionality when a RLP is applied to a gateway. 

**Demo 1 overrides**

Using service registry. 
- Create a RateLimitPolicy that targets the gateway and a global rate limit for all hosts
- Show that this limit is applied to the service registry (with no RateLimitPolicy in their namespace)
- Create a RateLimitPolicy in the service registry namespace that targets the HTTPRoute of service and sets a different global rate limit rule plus a new limit for the upload path
- Show that the new limit takes effect
- Show that the RLP in the developer namespace shows the "Effective" policy based on what was applied at the gateway level

- [ ] Share demo and Design with Istio upstream and Gateway API

**Comment by maleck13** [comment]
@rahulanand16nov @eguzki would love your thoughts on these demo flows

**Comment by rahulanand16nov** [comment]
LPGTM :+1:

**Comment by eguzki** [comment]
Yeah, looks good.

**Comment by eguzki** [comment]
https://youtu.be/ZA3Lf3P0MuY
