### ISSUE TITLE
New API exposed via Kuadrant AuthPolicy that uses target ref concept

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#133]
This API should be an Alpha API that is intended to help us explore exposing our own AuthPolicy resource and come up with a design. 
The API should use the target ref policy attachment idea. 
We also need to think about what it would mean for this policy to be attached to a gateway resource and what kind of things we may want to allow as overrides and defaults. 

The outcome of this work should be a design doc with a diagram that outlines how the new proposed AuthPolicy will work and how it differentiates from the Istio AuthPolicy. How it will be used and the resources it will target. It should also cover things that we don't want to expose such as the source property and also the host option in the operations

**Comment by rahulanand16nov** [comment]
Old one
