### ISSUE TITLE
Support targeting a TLSRoute with the target ref

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#142]
**What**

support targeting the TLSRoute object with RLP

**Comment by maleck13** [comment]
no use case yet

**Comment by eguzki** [comment]
This is unexpected. I was assuming TLSRoute was the recommended option for production environments. Feels like plain HTTP is a deprecated protocol in favor of HTTP over TLS (or GRPC over TLS)

**Comment by maleck13** [comment]
Yeah HTTPRoute :

```
HTTPRoute is for multiplexing HTTP or terminated HTTPS connections. It's intended for use in cases where you want to inspect the HTTP stream and use HTTP request data for either routing or modification, for example using HTTP Headers for routing, or modifying them in-flight.
```


``` 
TLSRoute[¶](https://gateway-api.sigs.k8s.io/concepts/api-overview/#tlsroute)
TLSRoute is for multiplexing TLS connections, discriminated via SNI. It's intended for where you want to use the SNI as the main routing method, and are not interested in properties of the higher-level protocols like HTTP. The byte stream of the connection is proxied without any inspection to the backend.
````

So wondering if TLSRoute makes sense currently?

**Comment by eguzki** [comment]
Ok, I see. 

So, an Gateway may terminate TLS connections and then configure routing rules using HTTPRoute object based on HTTP level info (Host header, path,...) already available after decoding the channel. 

Thanks for the big picture
