### ISSUE TITLE
Implement targeting Gateway API Gateway

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#160]
**What**

Implement based on our investigation in https://github.com/Kuadrant/kuadrant-controller/issues/124

**Comment by eguzki** [comment]
Design to be implemented: 
* [latest](https://github.com/Kuadrant/kuadrant-controller/blob/main/doc/proposals/rlp-target-gateway-resource.md)
* [Permalink](https://github.com/Kuadrant/kuadrant-controller/blob/391d7e232ed09509df972512058b8e62a6e14806/doc/proposals/rlp-target-gateway-resource.md)
