### ISSUE TITLE
Document with examples the behaviour of RLP

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#172]
With RLP we have some user guides and also a design proposal. One doc I think we could use is a more end user focused doc explaining how RLP works and the behaviour it applies when targeting a single HTTPRoute a single Gateway or a Gateway and HTTPRoute. Additionally if there are known limitations we should also document these.

**Comment by eguzki** [comment]
Currently we have:
* [Proposal doc](https://github.com/Kuadrant/kuadrant-controller/blob/main/doc/proposals/rlp-target-gateway-resource.md): explaining how RLP works and the behaviour it applies when targeting a single HTTPRoute a single Gateway
* Demo user guide: https://github.com/Kuadrant/kuadrant-controller/blob/main/doc/demo-rlp-target-gateway.md

I think we need to compile a user oriented doc with the same content
