### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-controller#45]
Doc: https://docs.google.com/document/d/1oLZeXLf30WlOD1TNFhrVJoZdgsZOMdtIXw4GnRbYQkk/edit?usp=sharing

Publicly available [here](https://docs.google.com/document/d/e/2PACX-1vT92063BMI_2503czrwTrvbGjhaHFpBSBAWC1nED2ygKoDRBh7gc0mJDL5yybMDZ7I6Bs_akjsYiuAV/pub)

**Comment by unleashed** [comment]
There has been previous work exploring the design space for rate limiting that could be useful to inform this feature in Kuadrant.

You might want to check out [the relevant issue in Ostia](https://github.com/3scale-labs/ostia/issues/17) as well as the linked issues which deal with several aspects therein.

**Comment by eguzki** [comment]
First implementation in https://github.com/Kuadrant/kuadrant-controller/pull/48
