### ISSUE TITLE
local development set up instructions

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#49]
Hey guys,

I followed the local setup instructions and wanted to offer some feedback. 
1) I had to install kustomize locally for the make command to work
2) The image for authrino no longer existed. It was referencing v0.1.0-pre

Not sure if it is still the expected way to try this out locally, but thought I would report the issues. Happy to create a PR referencing the need to install kustomise. What image should it use for authrino?

**Comment by eguzki** [comment]
Hi, 

We need to add some doc. The existing doc is very likely to be outdated.

If you just want to try out kuadrant controller, try deploying with the CLI. You only need to have golang and kubectl installed. 

```
~/tmp took 5s vim-ruby ❯ go install github.com/kuadrant/kuadrantctl@latest
~/tmp took 2s vim-ruby ❯ kuadrantctl version
{"level":"info","ts":1632139592.8104966,"msg":"kuadrantctl version: 0.0.1"}
{"level":"info","ts":1632139592.834858,"msg":"Istio version: docker.io/istio/pilot:1.9.4"}
{"level":"info","ts":1632139592.8473878,"msg":"Authorino version: quay.io/3scale/authorino:v0.4.0"}
{"level":"info","ts":1632139592.8542366,"msg":"Limitador operator version: quay.io/3scale/limitador-operator:v0.1.1"}
{"level":"info","ts":1632139592.8542783,"msg":"Limitador version: 0.4.0"}
{"level":"info","ts":1632139592.8595898,"msg":"Kuadrant controller version: quay.io/eastizle/kuadrant-controller:v0.1.0"}
```

Then, install kuadrant

```
$ kuadrantct install
````

You must have an open session with kubectl to an k8s or OCP cluster. You will need also cluster admin rights. The CLI is installing all kuadrant dependencies in `kuadrant-system` namespace. I suggest to start with [kind](https://kind.sigs.k8s.io/docs/user/quick-start/)

When done, you can deploy kuadrant CR's like APIProduct and try it out.

**Comment by maleck13** [comment]
Thanks @eguzki  I will give this a go

**Comment by maleck13** [comment]
This looks to have worked much better thank you
