### ISSUE TITLE
When an APIProduct is created with multiple APIs we should ensure the APIs are different at the mapping level

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#68]
Currently if  APIs are added to an APIProduct, we check the API Object exists and the target service exists. When more than one API is added to an APIProduct we should also do some verification that these individual APIs will form a valid APIProduct.

A key one would be to check each API has some form of unique mapping (header, method or path based routing). If there is no mapping we should probably reject the APIProduct

**Comment by eguzki** [comment]
this issue no longer applies
