### ISSUE TITLE
Controller can run into OOM if supplied with big enough OAS

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-controller#72]
The installer (kuadrantctl) install controller with a 40MB of RAM limit, which is not enough for general use. I tried using `petstore-expanded.yaml`  OAS (https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore-expanded.yaml) and the OpenShift killed it with OOM, I think increasing limits would be great.

Note: After using the OAS I am seeing the controller take about 100mb of RAM and for current testing, I set it to 200mb just to be sure

**Comment by eguzki** [comment]
It is actually 30Mb limit https://github.com/Kuadrant/kuadrantctl/blob/main/kuadrantmanifests/autogenerated/kuadrant.yaml#L662

We will increase it or process the OAS in a stream way instead of loading in memory before processing it.

**Comment by eguzki** [comment]
no longer applies
